name: Test
concurrency: production


on:
  push:
    branches: [ main ]
  pull_request :
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: action/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'

      - run: npm ci
      - run: npm run test